// Central icon registry — maps semantic app concepts to HugeIcons glyphs so the
// rest of the app never imports raw icon names. Swap a glyph here to change it
// everywhere. Powered by @hugeicons/core-free-icons (round stroke style).

import {
  DashboardSquare01Icon,
  UserMultiple02Icon,
  StudentsIcon,
  Note01Icon,
  CheckmarkCircle02Icon,
  Calendar03Icon,
  Calendar04Icon,
  MoneyBag02Icon,
  WalletAdd01Icon,
  Book02Icon,
  LibraryIcon,
  Bus01Icon,
  Navigation03Icon,
  Briefcase01Icon,
  BedSingle01Icon,
  Building06Icon,
  AssignmentsIcon,
  Analytics01Icon,
  ChartLineData01Icon,
  Message02Icon,
  BubbleChatIcon,
  Settings02Icon,
  UserSettings01Icon,
  Award01Icon,
  Clock01Icon,
  Search01Icon,
  Add01Icon,
  Download04Icon,
  FilterIcon,
  Menu01Icon,
  Notification03Icon,
  Logout03Icon,
  ArrowLeft02Icon,
  MortarboardIcon,
  TeacherIcon,
  Home01Icon,
  Shield01Icon,
  UserCheck01Icon,
  IdentityCardIcon,
  Megaphone01Icon,
  Sun01Icon,
  CheckmarkBadge01Icon,
  Quiz01Icon,
  Certificate01Icon,
  Location01Icon,
  Task01Icon,
  UserGroupIcon,
  PencilEdit02Icon,
  Backpack01Icon,
  School01Icon,
  Sofa01Icon,
  Alert01Icon,
  Wallet01Icon,
  Invoice01Icon,
  FavouriteIcon,
  GridViewIcon,
  CheckmarkSquare01Icon,
  Cancel01Icon,
  Mail01Icon,
  WhatsappIcon,
  SmartPhone01Icon,
  Pin02Icon,
  Coffee02Icon,
  Restaurant01Icon,
  Dish01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Image01Icon,
  PaintBoardIcon,
  CloudUploadIcon,
  ComplaintIcon,
  Album02Icon,
  RestaurantTableIcon,
  PackageSearchIcon,
  UserCircleIcon,
  TeachingIcon,
} from '@hugeicons/core-free-icons'

export const ICON = {
  // modules / nav
  dashboard: DashboardSquare01Icon,
  students: StudentsIcon,
  admissions: Note01Icon,
  attendance: CheckmarkCircle02Icon,
  gradebook: Award01Icon,
  fees: MoneyBag02Icon,
  timetable: Calendar03Icon,
  library: LibraryIcon,
  transport: Bus01Icon,
  hr: Briefcase01Icon,
  hostel: BedSingle01Icon,
  assignments: AssignmentsIcon,
  analytics: Analytics01Icon,
  communication: Message02Icon,
  settings: Settings02Icon,
  features: GridViewIcon,
  studyMaterial: TeachingIcon,
  infraction: ComplaintIcon,
  gallery: Album02Icon,
  foodMenu: RestaurantTableIcon,
  lostFound: PackageSearchIcon,
  account: UserCircleIcon,

  // roles
  admin: Shield01Icon,
  teacher: TeacherIcon,
  student: MortarboardIcon,
  parent: UserGroupIcon,

  // misc / KPI glyphs
  people: UserMultiple02Icon,
  teacherPeople: TeacherIcon,
  chart: ChartLineData01Icon,
  wallet: Wallet01Icon,
  walletAdd: WalletAdd01Icon,
  invoice: Invoice01Icon,
  clock: Clock01Icon,
  calendar: Calendar04Icon,
  exam: Quiz01Icon,
  certificate: Certificate01Icon,
  book: Book02Icon,
  route: Navigation03Icon,
  location: Location01Icon,
  building: Building06Icon,
  bed: BedSingle01Icon,
  sofa: Sofa01Icon,
  task: Task01Icon,
  edit: PencilEdit02Icon,
  backpack: Backpack01Icon,
  school: School01Icon,
  megaphone: Megaphone01Icon,
  chat: BubbleChatIcon,
  bell: Notification03Icon,
  award: Award01Icon,
  idcard: IdentityCardIcon,
  userCheck: UserCheck01Icon,
  userSettings: UserSettings01Icon,
  sun: Sun01Icon,
  badge: CheckmarkBadge01Icon,
  home: Home01Icon,
  alert: Alert01Icon,
  heart: FavouriteIcon,
  check: CheckmarkSquare01Icon,
  cross: Cancel01Icon,
  whatsapp: WhatsappIcon,
  mail: Mail01Icon,
  sms: SmartPhone01Icon,
  pin: Pin02Icon,
  breakfast: Coffee02Icon,
  lunch: Restaurant01Icon,
  dinner: Dish01Icon,
  arrowUp: ArrowUp01Icon,
  arrowDown: ArrowDown01Icon,
  image: Image01Icon,
  palette: PaintBoardIcon,
  upload: CloudUploadIcon,

  // actions
  search: Search01Icon,
  add: Add01Icon,
  download: Download04Icon,
  filter: FilterIcon,
  menu: Menu01Icon,
  logout: Logout03Icon,
  back: ArrowLeft02Icon,
}
